name: Java test reusable
on:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
